name: Auto Generate EN Blog Placeholders

on:
  push:
    branches:
      - main

jobs:
  generate-en-placeholders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Generate EN blog placeholders
        run: yarn gen-en-blog

      - name: Commit and push generated files
        run: |
          git config --global user.name 'System Administrator'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add en/blog/
          git reset en/blog/index.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-generate en blog placeholders"
            git push
          fi
