name: Deploy VitePress Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 遷出程式碼
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 設定 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: 切換到根目錄
        run: cd "$GITHUB_WORKSPACE"

      - name: 安裝相依套件
        run: yarn install
        working-directory: ${{ github.workspace }}

      - name: 建置 VitePress 網站
        run: yarn run build
        working-directory: ${{ github.workspace }}

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .vitepress/dist
          clean: true
