name: Deploy VitePress Site to GitHub Pages

on:
  push:
    branches:
      - main # 請根據您的專案調整：如果您的主要分支是 master，請將 main 改為 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install # 請根據您的專案調整：如果您使用 yarn，請改為 yarn install

      - name: Build VitePress site
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist # 請根據您的專案調整：VitePress 預設的輸出目錄是 .vitepress/dist。如果您的設定不同，請修改此路徑。
          force_orphan: true
