name: Deploy VitePress Site to GitHub Pages

on:
  push:
    branches:
      - main # 您的主要分支名稱
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Change working directory to root
        run: cd "$GITHUB_WORKSPACE"

      - name: Print current working directory
        run: pwd

      - name: Install dependencies
        run: yarn install

      - name: Check for yarn.lock and commit if missing
        run: |
          if [ ! -f yarn.lock ]; then
            echo "yarn.lock 文件不存在，正在嘗試建立..."
            yarn install --lock-file
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add yarn.lock
            git commit -m "自動建立 yarn.lock 文件"
            git push origin main
          fi

      - name: Build VitePress site
        run: yarn build
        working-directory: ${{ github.workspace }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # 部署到 main 分支
          folder: .vitepress/dist # VitePress 的輸出目錄，請根據您的實際設定調整
          clean-exclude: .nojekyll # 排除 .nojekyll 檔案，如果需要
