permissions:
  contents: write
  actions: read

name: 部署 VitePress 靜態網站到 GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  full-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 遷出程式碼
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 部屬日誌
        run: |
          deleted_any=0
          for en_file in en/blog/*.md; do
            [ ! -f "$en_file" ] && continue
            base_file="blog/$(basename "$en_file")"
            if [ ! -f "$base_file" ]; then
              git rm "$en_file"
              echo "Deleted $en_file (orphan)"
              deleted_any=1
            fi
          done
          if [ $deleted_any -eq 1 ]; then
            git config --global user.name 'System Administrator'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -am "chore: sync delete en/blog files"
            git pull --rebase origin main
            git push || git push --force
          else
            echo "No en/blog files to delete."
          fi
          
      - name: 設定 Node.js 與快取
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 安裝相依套件
        run: yarn install

      - name: 產生 sidebar.generated.ts
        run: node .vitepress/components/generateSidebar.cjs

      - name: Commit 並 push sidebar.generated.ts（如有變更）
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .vitepress/sidebar.generated.ts
          if git diff --cached --quiet; then
            echo "沒有側邊欄變更，無需提交"
          else
            git commit -m "chore: 自動產生 sidebar.generated.ts"
            git pull --rebase origin main
            git push
          fi

      - name: Commit 並 push yarn.lock
        run: |
          git config --global user.name 'System Administrator'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if git diff --quiet yarn.lock; then
            echo "No changes to yarn.lock."
          else
            git add yarn.lock
            git commit -m "chore: update yarn.lock [bot]"
            git pull --rebase origin main
            git push || git push --force
          fi

      - name: 保護、產生、還原並遞交英文 Blog 檔案
        shell: /usr/bin/bash -e {0}
        run: |
          # --- 階段 1: 保護已有人工編輯的英文檔案 ---
          PROTECTED_DIR="tmp_protected_en_files"
          mkdir -p "$PROTECTED_DIR"
          echo "=> 階段 1: 檢查並保護已有人工編輯的英文文章..."
          
          if [ -d "en/blog" ]; then
            for file in en/blog/*.md; do
              [ -f "$file" ] || continue
              # 檢查檔案的完整歷史紀錄中是否包含非機器人作者
              human_authors=$(git log --follow --pretty=format:"%an" -- "$file" | grep -v -E "\[bot\]|System Administrator")
              
              if [ -n "$human_authors" ]; then
                echo "    - 保護檔案: $file (因偵測到人工編輯紀錄)"
                mv "$file" "$PROTECTED_DIR/"
              fi
            done
          else
            echo "    - en/blog/ 目錄不存在，跳過保護程序。"
          fi

          # --- 階段 2: 產生遞補檔案 ---
          echo "=> 階段 2: 執行遞補檔案產生程序 (yarn gen-en-blog)..."
          yarn gen-en-blog
          echo "    - 產生程序完成。"

          # --- 階段 3: 還原受保護的檔案 ---
          echo "=> 階段 3: 還原受保護的人工編輯檔案..."
          # 檢查備份目錄是否為空
          if [ -n "$(ls -A $PROTECTED_DIR 2>/dev/null)" ]; then
            # 將備份的檔案移回原位，覆蓋掉產生器產生的空白檔
            mv -f "$PROTECTED_DIR"/* en/blog/
            echo "    - 已還原受保護的檔案。"
          else
            echo "    - 沒有需要還原的檔案。"
          fi
          # 清理暫存目錄
          rm -rf "$PROTECTED_DIR"
          
          # --- 階段 4: Commit 並 Push 變更 ---
          echo "=> 階段 4: 檢查是否有新檔案需要提交..."
          git config --global user.name 'System Administrator'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add en/blog/

          if git diff --cached --quiet; then
            echo "    - 沒有新產生的遞補檔案需要提交。"
          else
            echo "    - 偵測到新產生的遞補檔案，正在提交..."
            git commit -m "chore: auto-generate en blog placeholders"
            git pull --rebase origin main
            git push --set-upstream origin main || git push
            echo "    - 新檔案已成功提交。"
          fi

      - name: 清除 Vite/VitePress 快取
        run: |
          rm -rf .vitepress/.cache .vitepress/dist .vite node_modules/.vite

      - name: 建置 VitePress 網站
        run: yarn run build

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .vitepress/dist
          clean: true
          
      # --- 偵測新文章並通知 Telegram ---
      - name: 偵測新文章
        id: detect-new-files
        run: |
          TARGET_DIR="blog/"
          CURRENT_SHA="${{ github.sha }}"
          LAST_COMMIT_SHA=$(git rev-parse "${{ github.event.before }}" 2>/dev/null || git rev-parse "${CURRENT_SHA}~1" 2>/dev/null || echo "")
          OUTPUT_FILE="new_post_files.txt"
          DETECTED_FILES=""
          if [ -z "$LAST_COMMIT_SHA" ] || [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            DETECTED_FILES=$(git diff --name-only --diff-filter=A "${CURRENT_SHA}~1" "${CURRENT_SHA}" -- "$TARGET_DIR")
          else
            DETECTED_FILES=$(git diff --name-only --diff-filter=A "${LAST_COMMIT_SHA}" "${CURRENT_SHA}" -- "$TARGET_DIR")
          fi
          echo "$DETECTED_FILES" | grep . > "$OUTPUT_FILE" || true
          if [ -s "$OUTPUT_FILE" ]; then
            echo "偵測到新文章，列表已儲存至 $OUTPUT_FILE"
            echo "has_new_files=true" >> $GITHUB_ENV
          else
            echo "沒有偵測到新文章"
            echo "has_new_files=false" >> $GITHUB_ENV
          fi

      - name: 處理並發送 Telegram 通知
        if: env.has_new_files == 'true'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -e
          NEW_POST_FILES=$(cat new_post_files.txt)
          if [ -z "$NEW_POST_FILES" ]; then
            echo "文章列表為空，中止執行。"
            exit 0
          fi
          BASE_URL="https://holybear.me"
          escape_markdownv2() {
            printf "%s" "$1" | sed -e 's/[\\_*\[\]()~`>#+\-=|{}.!]/\\&/g'
          }
          for file_path in $NEW_POST_FILES; do
            echo "Processing file: $file_path"
            file_content=$(cat "$file_path")
            TITLE=$(echo "$file_content" | awk -F': ' '/^title:/ {print $2; exit}')
            if [ -z "$TITLE" ]; then
              TITLE=$(echo "$file_content" | awk -F'# ' '/^# / {print $2; exit}')
            fi
            [ -z "$TITLE" ] && TITLE="無標題文章"
            CATEGORY=""
            CATEGORY=$(echo "$file_content" | grep -A 1 -iE '^\s*category:' | grep -E '^\s*-\s*' | head -n1 | sed -E 's/^\s*-\s*(.*)/\1/')
            [ -z "$CATEGORY" ] && CATEGORY=$(echo "$file_content" | grep -iE '^\s*category:\s*\[.*\]' | sed -E 's/.*\[\s*([^, ]*).*/\1/')
            [ -z "$CATEGORY" ] && CATEGORY=$(echo "$file_content" | grep -iE '^\s*category:\s*[^-\[]+' | head -n1 | sed -E 's/^\s*category:\s*//')
            CATEGORY=$(echo "$CATEGORY" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | sed -E 's/[\x27"\/]//g')
            if [ -n "$CATEGORY" ]; then
              TITLE="【${CATEGORY}】${TITLE}"
            fi
            ARTICLE_SLUG=$(echo "$file_path" | sed -E 's|^blog/(.*)\.md$|\1|')
            ARTICLE_URL="${BASE_URL}/blog/${ARTICLE_SLUG}"
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            AUTHOR_NAME=$(git log -1 --pretty=%an)
            ESCAPED_TITLE=$(escape_markdownv2 "$TITLE")
            ESCAPED_COMMIT_MESSAGE=$(escape_markdownv2 "$COMMIT_MESSAGE")
            ESCAPED_AUTHOR_NAME=$(escape_markdownv2 "$AUTHOR_NAME")
            MESSAGE=$'*📢 New push to GitHub*\n'
            MESSAGE+=$'*'"${ESCAPED_TITLE}"$'*\n'
            MESSAGE+=$'```commit\n'"${ESCAPED_COMMIT_MESSAGE}"$'\n```'
            MESSAGE+=$'[➡️ 點此閱讀文章]('"${ARTICLE_URL}"$')\n'
            MESSAGE+='by `'"${ESCAPED_AUTHOR_NAME}"'`'
            RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
              --data-urlencode "text=${MESSAGE}" \
              --data-urlencode "parse_mode=MarkdownV2" \
              --data-urlencode "disable_web_page_preview=true")
            if echo "$RESPONSE" | grep -q '"ok":true'; then
              echo "✅ Telegram notification sent successfully for: $file_path"
            else
              echo "❌ Failed to send Telegram notification for: $file_path"
              echo "Telegram API Response: $RESPONSE"
            fi
          done
