name: 部署 VitePress 靜態網站到 GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  full-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 遷出程式碼
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 設定 Node.js 與快取
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: 安裝相依套件
        run: yarn install

      # 1. 先產生英文 Blog 遞補檔案
      - name: 產生英文 Blog 遞補檔案
        run: yarn gen-en-blog

      # 2. Commit 並 push 產生的檔案（如果有更動）
      - name: Commit 並 push 產生的檔案
        run: |
          git config --global user.name 'System Administrator'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add en/blog/
          git reset en/blog/index.md
          git checkout -- en/blog/index.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-generate en blog placeholders"
            git pull --rebase origin main
            git push --set-upstream origin main || git push
          fi

      # 3. 建置 VitePress 網站前先清除快取
      - name: 清除 Vite/VitePress 快取
        run: |
          rm -rf .vitepress/.cache .vitepress/dist .vite node_modules/.vite

      # 4. 建置 VitePress 網站
      - name: 建置 VitePress 網站
        run: yarn run build

      # 5. 部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .vitepress/dist
          clean: true
