name: Deploy VitePress Site to GitHub Pages

on:
  push:
    branches:
      - main # 你的主要分支名稱
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 遷出程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: 切換到根目錄
        run: cd "$GITHUB_WORKSPACE"

      - name: 安裝相依套件
        run: yarn install
        working-directory: ${{ github.workspace }} # 明確設定工作目錄

      - name: 建置 VitePress 網站
        run: yarn run build
        working-directory: ${{ github.workspace }}

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # 部署到 gh-pages 分支
          folder: .vitepress/dist # VitePress 的輸出目錄
          clean: true # 清理先前部署的檔案 (建議開啟)
