name: Notify New Blog Post to Telegram

on:
  workflow_run:
    workflows: ["部署 VitePress 靜態網站到 GitHub Pages"] # 監聽的 workflow 名稱
    types:
      - completed

jobs:
  notify_new_post:
    runs-on: ubuntu-latest
    # 只有在部署成功時才執行此 job
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: 下載新文章列表產物
        uses: actions/download-artifact@v4
        with:
          name: new-post-files
          path: .
      
      - name: 檢查是否有新文章
        id: check-files
        run: |
          if [ -s new_post_files.txt ] && [ -n "$(cat new_post_files.txt)" ]; then
            echo "偵測到新文章列表，準備發送通知。"
            echo "has_new_files=true" >> "$GITHUB_OUTPUT"
          else
            echo "無新文章，不需通知。"
            echo "has_new_files=false" >> "$GITHUB_OUTPUT"
          fi

      - name: 遷出特定 Commit 的程式碼
        if: steps.check-files.outputs.has_new_files == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }} # 遷出觸發部署流程的那個 commit

      - name: 處理並發送 Telegram 通知
        if: steps.check-files.outputs.has_new_files == 'true'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -e
          NEW_POST_FILES=$(cat new_post_files.txt)
          if [ -z "$NEW_POST_FILES" ]; then
            echo "文章列表為空，中止執行。"
            exit 0
          fi
          
          # ... (下方為與您原檔案完全相同的發送邏輯) ...
          
          BASE_URL="https://holybear.me"
          escape_markdownv2() {
            printf "%s" "$1" | sed -e 's/[\\_*\[\]()~`>#+\-=|{}.!]/\\&/g'
          }
          for file_path in $NEW_POST_FILES; do
            echo "Processing file: $file_path"
            file_content=$(cat "$file_path")
            TITLE=$(echo "$file_content" | awk -F': ' '/^title:/ {print $2; exit}')
            if [ -z "$TITLE" ]; then
              TITLE=$(echo "$file_content" | awk -F'# ' '/^# / {print $2; exit}')
            fi
            [ -z "$TITLE" ] && TITLE="無標題文章"
            CATEGORY=""
            CATEGORY=$(echo "$file_content" | grep -A 1 -iE '^\s*category:' | grep -E '^\s*-\s*' | head -n1 | sed -E 's/^\s*-\s*(.*)/\1/')
            [ -z "$CATEGORY" ] && CATEGORY=$(echo "$file_content" | grep -iE '^\s*category:\s*\[.*\]' | sed -E 's/.*\[\s*([^, ]*).*/\1/')
            [ -z "$CATEGORY" ] && CATEGORY=$(echo "$file_content" | grep -iE '^\s*category:\s*[^-\[]+' | head -n1 | sed -E 's/^\s*category:\s*//')
            CATEGORY=$(echo "$CATEGORY" | sed -E 's/^[[:space:]]+|[[:space:]]+$//g' | sed -E 's/[\x27"\/]//g')
            if [ -n "$CATEGORY" ]; then
              TITLE="【${CATEGORY}】${TITLE}"
            fi
            ARTICLE_SLUG=$(echo "$file_path" | sed -E 's|^blog/(.*)\.md$|\1|')
            ARTICLE_URL="${BASE_URL}/blog/${ARTICLE_SLUG}"
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            AUTHOR_NAME=$(git log -1 --pretty=%an)
            ESCAPED_TITLE=$(escape_markdownv2 "$TITLE")
            ESCAPED_COMMIT_MESSAGE=$(escape_markdownv2 "$COMMIT_MESSAGE")
            ESCAPED_AUTHOR_NAME=$(escape_markdownv2 "$AUTHOR_NAME")
            MESSAGE=$'*📢 New push to GitHub*\n'
            MESSAGE+=$'*'"${ESCAPED_TITLE}"$'*\n'
            MESSAGE+=$'```commit\n'"${ESCAPED_COMMIT_MESSAGE}"$'\n```'
            MESSAGE+=$'[➡️ 點此閱讀文章]('"${ARTICLE_URL}"$')\n'
            MESSAGE+='by `'"${ESCAPED_AUTHOR_NAME}"'`'
            RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
              --data-urlencode "text=${MESSAGE}" \
              --data-urlencode "parse_mode=MarkdownV2" \
              --data-urlencode "disable_web_page_preview=true")
            if echo "$RESPONSE" | grep -q '"ok":true'; then
              echo "✅ Telegram notification sent successfully for: $file_path"
            else
              echo "❌ Failed to send Telegram notification for: $file_path"
              echo "Telegram API Response: $RESPONSE"
            fi
          done
